export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const GET_JEWELLERYS = "GET_JEWELLERYS";
export const JEWELLERYS_ERROR = "JEWELLERYS_ERROR";

export const GET_ELECTRONICS = "GET_ELECTRONICS";
export const ELECTRONICS_ERROR = "ELECTRONICS_ERROR";

export const GET_MENCLOTHING = "GET_MENCLOTHING";
export const MENCLOTHING_ERROR = "MENCLOTHING_ERROR";

export const GET_WOMENCLOTHING = "GET_WOMENCLOTHING";
export const WOMENCLOTHING_ERROR = "WOMENCLOTHING_ERROR";